// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApiRestTesting.Data;

#nullable disable

namespace MyApiRestTesting.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApiRestTesting.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("EmailAdress")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL_ADDRESS");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FULL_NAME");

                    b.HasKey("CustomerId");

                    b.ToTable("CUSTOMERS");
                });

            modelBuilder.Entity("MyApiRestTesting.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ORDER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ORDER_STATUS");

                    b.Property<DateTime?>("OrderTimestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("ORDER_TMS");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("STORE_ID");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("MyApiRestTesting.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_ID");

                    b.Property<int>("LineItemId")
                        .HasColumnType("int")
                        .HasColumnName("LINE_ITEM_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<int?>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("SHIPMENT_ID");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("OrderId", "LineItemId");

                    b.ToTable("ORDERS_ITEMS");
                });

            modelBuilder.Entity("MyApiRestTesting.Models.Entities.Order", b =>
                {
                    b.HasOne("MyApiRestTesting.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MyApiRestTesting.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("MyApiRestTesting.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MyApiRestTesting.Models.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MyApiRestTesting.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
